eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.client.discovery: DEBUG